---
title: "Obligatory Exercise 2"
subtitle: "TMA4275 Lifetime analysis Spring 2019 "
author: "Martin Outzen Berild"
date: "23 mars 2019"
output: html_document
---

```{r setup, include=FALSE}
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
#rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(survival)
library(survminer)
library(kableExtra)
library(dplyr)
library(SurvRegCensCov)
library(flexsurv)
```
## a)
```{r}
lungcancer.df <- as.data.frame(
  read.table("../data/TMA4275VeteranLungCancer.txt", 
             header = TRUE))
KM0 <- survfit(Surv(Y, C) ~ Treat,  
               type="kaplan-meier", 
               conf.type="log", 
               data=lungcancer.df)
ggsurvplot(KM0, data = lungcancer.df)

treat.median <- summary(KM0)$table[, "median"]
treat.expected <- summary(KM0)$table[, "*rmean"]
table.treat <- data.frame(treatment = names(treat.median),
                           median = unname(treat.median),
                           expected = unname(treat.expected))
kable(table.treat,
      caption = "\\label{tab:treat}Estimated median and expected 
      lifetime by treatment") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", 
                                      "condensed","responsive"),
                full_width = F,position = "center")
```
```{r}
KM1 <- survfit(Surv(Y, C) ~ Cell,  
               type="kaplan-meier", 
               conf.type="log", 
               data=lungcancer.df)
ggsurvplot(KM1, data = lungcancer.df)
cell.median <- summary(KM1)$table[, "median"]
cell.expected <- summary(KM1)$table[, "*rmean"]
table.cell <- data.frame(treatment = names(cell.median),
                           median = unname(cell.median),
                           expected = unname(cell.expected))
kable(table.cell,
      caption = "\\label{tab:cell}Estimated median 
      and expected lifetime by cell type") %>% 
  kable_styling(bootstrap_options = c("striped", "hover",
                                      "condensed","responsive"),
                full_width = F,position = "center")
```
## b)

```{r}
wei.lung<-survreg(Surv(Y,C) ~ Treat + PS + Month+  Age + Prior + factor(Cell), data = lungcancer.df, dist = "weibull")
coef <- wei.lung$coefficients
lifeWeil <- function(data, coef){
  x = c(1,data$Treat, data$PS, data$Month, data$Age, data$Prior,as.numeric(data$Cell==2),
        as.numeric(data$Cell==3),as.numeric(data$Cell==4))
  return(exp(as.numeric(coef)%*%x))
}
lifeWeil(lungcancer.df[1,],coef)
lifetime1 = coef["Treat"] + coef["PS"] + coef["Age"] + Coef["Prior"]
```

```{r}
table.b <- data.frame(Levels.of.Cell = c(1,2,3,4), x2 =c(0,1,0,0), x3 = c(0,0,1,0), x4 = c(0,0,0,1))
kable(table.b,align=rep('c', 4),
      caption = "\\label{tab:b}Estimated median 
      and expected lifetime by cell type") %>% 
  kable_styling(bootstrap_options = c("striped", "hover",
                                      "condensed","responsive"),
                full_width = F,position = "center")
```
## c)
```{r}
summary(wei.lung)
```

## d)
```{r}
fit.coxph <- survreg(Surv(Y,C) ~ Treat + PS+ Month + Age + Prior + factor(Cell), data = lungcancer.df)

#ggforest(fit.coxph, data = lungcancer.df)
```
## e)

## f)

